### ISSUE TITLE
Todo List by next session

### ISSUE THREAD

**Issue by rhelmstedter** [Gris-Sombrero/PDI_Capstone#2]
- [ ] add subtract feature
- [ ] add view feature
- [ ] add goal feature
- [ ] add, commit, push it up to GitHub
- [ ] start a pull request and assign me to review
- [ ] finish the newbies 1-50
